### ISSUE TITLE
Remove dependency on circe-generic

### ISSUE THREAD

**Issue by kubukoz** [kubukoz/sup#127]
Circe instances could and should be hand-written, currently it should be easy to do with `Decoder.forProduct2` and the corresponding Encoder function.

**Comment by mfirry** [comment]
Why do you think they should/could be hand-written, if I may ask?

**Comment by calvinlfer** [comment]
it is  never a good idea to use auto generation because if a user comes in and changes a case class, they will change the JSON unknowingly. It's better to disconnect them like this so you end up with some sort of a compile error if you add or remove fields

**Comment by mfirry** [comment]
Thanks. I just never thought about it. Never really offered a library that was using circe encoders. Thanks.

**Comment by kubukoz** [comment]
Closed by #129
