### ISSUE TITLE
Move build to sbt-github-actions

### ISSUE THREAD

**Issue by kubukoz** [kubukoz/sup#296]
Travis CI has had its time, but I've had a better experience with GitHub Actions and Daniel's generative sbt plugin. We should migrate the build to use that instead.

The obvious issue with the migration that I can foresee is the microsite, which might require some extra dependencies like sass & jekyll. It's probably a good idea to start without the site and then we'll add it once we have the Actions working.

Some inspiration:

- https://github.com/ocadotechnology/sttp-oauth2
- https://github.com/kubukoz/slick-effect
- https://github.com/kubukoz/caliban-gitlab

**Comment by kubukoz** [comment]
Some extra notes if you want to work on it @amsayk:

- https://github.com/djspiewak/sbt-github-actions/
- https://github.com/olafurpg/sbt-ci-release

We'll need to add secrets to the repo, but that can be done after everything is set up in the code. Probably the best starting point is to copy-paste the changes from https://github.com/kubukoz/slick-effect/commit/149ea9c20ae008873f4a1a2c1cf35603c9866bc8 .

In general, this will require some changes to the build e.g. moving `crossScalaVersions` to `ThisBuild/` instead of the individual projects. We also need to make sure we're cross-compiling **everything** to the same set of Scala versions, as that's the only thing that works. Again, this might be a problem for the microsite, we'll see. Maybe the site can be built in a separate job or something, for starters let's skip the site completely.

**Comment by amsayk** [comment]
Hi @kubukoz, I'll take work on this.

**Comment by amsayk** [comment]
I will work on the site on a separate pull request.

**Comment by kubukoz** [comment]
Closed in #299. Many thanks!
