### ISSUE TITLE
Cassandra HealthCheck for Cats Effect 2.X

### ISSUE THREAD

**Issue by ionutioio** [kubukoz/sup#361]
Hello, 
I have created a healthcheck module for Cassandra, but based on cats effect 2.X because that's what my other projects use.
Is it possible to create a v0.8.1 release with it? 
I also have the code for the Cats Effect 3 version, but I cannot test it nor use it on my other projects. 
Could you please create a branch for the 0.8.x version so that I can create a pull request? 
I can contribute the cats effect 3 version shortly afterwards if you please.
I am at your disposal for any questions or remarks.

**Comment by kubukoz** [comment]
Hi, unfortunately we had the migration to GitHub Actions between 0.8.0 and 0.9.0-M1, so we can't start from 0.8.0 - but I have an idea.

I took all of 0.9.0 and removed the commits that were binary breaking wrt 0.8.0:

- updates of cats-tagless
- updates of CE
- updates of sttp (not present in core)

This is now at `series/0.8.x`. Please review which version of cats-tagless you have (it's a core dependency) and, if 0.11 is fine, you can make a PR to that branch. If you have 0.12 or 0.13 I think we can go with the `0.8-012.0` naming strategy.

**Comment by ionutioio** [comment]
Hello, 
Thank you for your reply! I have created the 2 pull requests: one targeting series/0.8.x and one targeting main.

Should you accept my PRs, could you please release a 0.8.1 to maven central so that I can use it in my projects please?
Thank you again for your help

**Comment by kubukoz** [comment]
This is done and released in 0.8.1 (CE2) and 0.9.0-M3 (CE3).
