### ISSUE TITLE
akka-http router module

### ISSUE THREAD

**Issue by kubukoz** [kubukoz/sup#39]
It would be nice to support akka-http routes for any health check kind. The code would look quite similar to the http4s module.

**Comment by DennisVDB** [comment]
Implementing this for any effect type `F` is a bit problematic. Akka-HTTP expects a `Future` which I'm not sure how to get from `F`. Short of passing `unsafeToFuture: F[A] => Future[A]` to `akkaHttp.healthCheckRoutes` would you have another idea?

**Comment by kubukoz** [comment]
Hi! Thanks for your interest in this.

`F[A] => Future[A]` is one option, an alternative is `F ~> Future`, but I think it's best if we go with `implicit F: cats.effect.Effect[F]` (and then go through `fa.toIO.unsafeToFuture()` :)

In fact, I'd like to have both the `Effect` variant and something that takes an argument of the shape `Request => F ~> Future` - I can imagine a use-case for not having `Effect` e.g. if your F is `Kleisli[IO, TraceContext, ?]`, and you get the TraceContext from the request.
