### ISSUE TITLE
Dependencies stalled

### ISSUE THREAD

**Issue by pacdaemon** [kubukoz/sup#528]
I can see there are some PRs coming from dependency bot, scala-steward open. Some of those are ready to merge, some others have conflicts. I like the project and I'm using it, so I wonder if I can somehow help. I can consolidate every dependency update into a single PR if that makes things easy.

**Comment by kubukoz** [comment]
That would help a lot for sure.

Probably the easiest way would be to use https://github.com/kitlangton/scala-update.

**Comment by kubukoz** [comment]
Closed in https://github.com/kubukoz/sup/pull/529

**Comment by pacdaemon** [comment]
Thank you for the release! I didn't know https://github.com/kitlangton/scala-update.  💯
